[package]
name = "fixedbuf"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Fixed length buffer with capacity"

[dependencies]
bytes = "1"
byteorder = "1"
thiserror = "2"
