[package]
name = "zebra"
version = "0.6.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
bytes = "1"
ipnet = "2.9.0"
nom = "7"
nom-derive = "0.10"
rusticata-macros = "4"
prost = "0.11"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tonic = "0.9"
libyang = { git = "https://github.com/zebra-rs/libyang" }
regex = "1.10"
similar = "2"
dirs = "5"

[build-dependencies]
tonic-build = "0.9"
